// build.js — dijalankan saat Cloudflare Pages build
const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, 'public', 'js', 'config.js');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

console.log('=== build.js ===');
console.log('SUPABASE_URL:', supabaseUrl ? '✅ found' : '❌ NOT FOUND');
console.log('SUPABASE_ANON_KEY:', supabaseAnonKey ? '✅ found' : '❌ NOT FOUND');

if (!supabaseUrl || !supabaseAnonKey) {
  console.log('⚠️  Env vars missing, using existing config.js as-is.');
  console.log('Current config.js content:');
  console.log(fs.readFileSync(configPath, 'utf8'));
  process.exit(0);
}

const content = `// Auto-generated by build.js
const SUPABASE_URL = "${supabaseUrl}";
const SUPABASE_ANON_KEY = "${supabaseAnonKey}";
const API_URL = \`\${SUPABASE_URL}/functions/v1/api\`;
`;

fs.writeFileSync(configPath, content);
console.log('✅ config.js generated successfully');
console.log('API_URL will be:', `${supabaseUrl}/functions/v1/api`);
