// build.js — dijalankan saat Cloudflare Pages build
// Mengganti placeholder di config.js dengan env variables
const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, 'public', 'js', 'config.js');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.log('No env vars found, using existing config.js as-is.');
  process.exit(0);
}

const content = `// Auto-generated by build.js — do not edit manually
const SUPABASE_URL = "${supabaseUrl}";
const SUPABASE_ANON_KEY = "${supabaseAnonKey}";
const API_URL = \`\${SUPABASE_URL}/functions/v1/api\`;
`;

fs.writeFileSync(configPath, content);
console.log('config.js generated from environment variables.');
