// server.js — Dev server untuk local testing
require('dotenv').config();
const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 8080;
const PUBLIC_DIR = path.join(__dirname, 'public');
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

const configJs = `// Auto-generated by dev server dari .env
const SUPABASE_URL = "${SUPABASE_URL}";
const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";
const API_URL = \`\${SUPABASE_URL}/functions/v1/api\`;
`;

const mimeTypes = {
  '.html': 'text/html',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.mp3':  'audio/mpeg',
  '.wav':  'audio/wav',
};

const server = http.createServer((req, res) => {
  const urlPath = req.url.split('?')[0];

  // Inject config.js dari env
  if (urlPath === '/js/config.js') {
    res.writeHead(200, { 'Content-Type': 'application/javascript' });
    res.end(configJs);
    return;
  }

  // Tentukan file yang akan di-serve
  let targetFile;

  if (urlPath === '/admin' || urlPath === '/admin/') {
    targetFile = path.join(PUBLIC_DIR, 'admin.html');
  } else if (urlPath.startsWith('/haflah/') || urlPath === '/haflah') {
    targetFile = path.join(PUBLIC_DIR, 'haflah.html');
  } else if (urlPath === '/') {
    targetFile = path.join(PUBLIC_DIR, 'index.html');
  } else {
    targetFile = path.join(PUBLIC_DIR, urlPath);
    // Kalau file tidak ada → anggap slug undangan wedding → index.html
    if (!fs.existsSync(targetFile)) {
      targetFile = path.join(PUBLIC_DIR, 'index.html');
    }
  }

  const ext = path.extname(targetFile);
  const contentType = mimeTypes[ext] || 'application/octet-stream';

  fs.readFile(targetFile, (err, data) => {
    if (err) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('Not Found');
      return;
    }
    res.writeHead(200, { 'Content-Type': contentType });
    res.end(data);
  });
});

server.listen(PORT, () => {
  console.log(`\n✅ Dev server jalan di http://localhost:${PORT}`);
  console.log(`   Supabase URL : ${SUPABASE_URL}`);
  console.log(`   Admin panel  : http://localhost:${PORT}/admin`);
  console.log(`   Haflah       : http://localhost:${PORT}/haflah/nama-slug`);
  console.log(`   Wedding      : http://localhost:${PORT}/nama-slug\n`);
});
