// server.js — Dev server untuk local testing
// Serve folder public/ dan inject env vars ke config.js
require('dotenv').config();
const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 8080;
const PUBLIC_DIR = path.join(__dirname, 'public');

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

// Config.js content dibuat dari env vars
const configJs = `// Auto-generated by dev server dari .env
const SUPABASE_URL = "${SUPABASE_URL}";
const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";
const API_URL = \`\${SUPABASE_URL}/functions/v1/api\`;
`;

const mimeTypes = {
  '.html': 'text/html',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.mp3':  'audio/mpeg',
  '.wav':  'audio/wav',
};

const server = http.createServer((req, res) => {
  let urlPath = req.url.split('?')[0]; // strip query string

  // Inject config.js dari env
  if (urlPath === '/js/config.js') {
    res.writeHead(200, { 'Content-Type': 'application/javascript' });
    res.end(configJs);
    return;
  }

  // /admin → admin.html
  if (urlPath === '/admin' || urlPath === '/admin/') {
    urlPath = '/admin.html';
  }

  // /haflah/:slug → haflah.html
  if (urlPath.startsWith('/haflah/') || urlPath === '/haflah') {
    filePath = path.join(PUBLIC_DIR, 'haflah.html');
    const contentType = 'text/html';
    fs.readFile(filePath, (err, data) => {
      if (err) { res.writeHead(404); res.end('Not Found'); return; }
      res.writeHead(200, { 'Content-Type': contentType });
      res.end(data);
    });
    return;
  }

  // Root → index.html
  if (urlPath === '/') {
    urlPath = '/index.html';
  }

  let filePath = path.join(PUBLIC_DIR, urlPath);

  // Cek apakah file ada
  if (!fs.existsSync(filePath)) {
    // Kalau tidak ada, anggap sebagai slug undangan → serve index.html
    filePath = path.join(PUBLIC_DIR, 'index.html');
  }

  const ext = path.extname(filePath);
  const contentType = mimeTypes[ext] || 'application/octet-stream';

  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('Not Found');
      return;
    }
    res.writeHead(200, { 'Content-Type': contentType });
    res.end(data);
  });
});

server.listen(PORT, () => {
  console.log(`\n✅ Dev server jalan di http://localhost:${PORT}`);
  console.log(`   Supabase URL : ${SUPABASE_URL}`);
  console.log(`   Admin panel  : http://localhost:${PORT}/admin`);
  console.log(`\nContoh undangan (setelah buat di admin):`);
  console.log(`   http://localhost:${PORT}/nama-slug-undangan\n`);
});
